{% macro snapshot_rename_cols() %}

/* goal is to rename the columns automatically generated by dbt as well as set the valid_to to a far away date to help with join on clauses */

  dbt_scd_id as sk_id
, dbt_updated_at as updated_at
, dbt_valid_from as valid_from
, case 
    when dbt_valid_to is null then '2099-12-31' 
    else dbt_valid_to 
  end as valid_to

{% endmacro %}